### PR TITLE
vagrant-notify 0.5.0

### PR DESCRIPTION
**Pull request by alpha01**
As per https://github.com/fgrehm/vagrant-notify/issues/24#issuecomment-214990782 here is the PR :beers:

**IMPROVEMENTS**

  - Notification server runs as a daemon (fork() has been removed so it's compatible with Windows). [[GH-14]]
  - Windows support (beta) [[GH-14]]
  - Notification server is accessible only from localhost.
  - Notification server information is displayed each time vagrant is started and halted.
  - New plugin command. Ability to view notification server status, and ability for manual restart. [CLI](https://gist.github.com/alpha01/9b81caca694a2735e658f978c41600b5)
  - New notify-send example scripts for OS X and Windows

**BUG FIXES**

  - `vagrant suspend/resume` stops/starts notification server respectively. [[GH-18]]
  - Plugin causes VM boot to fail. [[GH-22]]

[GH-14]:https://github.com/fgrehm/vagrant-notify/issues/14
[GH-18]:https://github.com/fgrehm/vagrant-notify/issues/18
[GH-22]:https://github.com/fgrehm/vagrant-notify/pull/22

### CODE REVIEW

**Comment by alpha01** [comment]
I think Travis CI needs to be update so tests run on newer version of Ruby.

**Comment by fgrehm** [comment]
Thanks for the PR and welcome aboard! 🍻
LMK when u are ready to cut a release and send me you rubygems email so I can add you there 😄

**Comment by alpha01** [comment]
My rubygems email is root@rubyninja.org. This commit should be ready for release. I guess the only thing left if just updating the CI so the tests run on newer versions of Ruby. :beers:

**Comment by fgrehm** [comment]
Cool! Please ping me when you get to a green build and I'll hook u up with rubygems access!

**Comment by alpha01** [comment]
Alright, CI tests should be green. (Will be green once it's merged since a new build needs to be run as .travis.yml was modified). So now, all is needed my rubygems account root@rubyninja.org to have access to the project's gem, and I should be ready to cut a new release.

**Comment by eli007** [comment]
whats the status on this PR?

**Comment by alpha01** [comment]
I'm just waiting for @fgrehm to grant access to my rubygems account so account cut over a new release..

**Comment by fgrehm** [comment]
@alpha01 done!

**Pull request merged**
