### PR TITLE
config options for notification app

### PR DESCRIPTION
**Pull request by MekDrop**
I think it's easier would be not to write wrappers for notify-send app but to define them in Vagrantfile. So, I added few configuration options for plugin:
* sender_app - application name that sends notification
* sender_params_str - string that used to parse parameters for that application when sending notification
* sender_params_escape - do we need to escape all params?

If these parameters are not used, everything I think should work in old way.

I don't know ruby very well so, if there is something bad with my code, let me know. I'll try to improve.

### CODE REVIEW

**Comment by alpha01** [comment]
Wow, this is really awesome! I'll test these changes sometime later today or tomorrow, if everything looks good, I'll merge these changes and cut a new release.

**Comment by alpha01** [comment]
Sorry for the delay.  The only problem I see is that since now [notify-send.erb](https://github.com/fgrehm/vagrant-notify/pull/38/files#diff-3d124cf0a0698d683a981ef3fb889fb5) is doing all the filtering rather than passing everything as is to the notification server ([server.rb](https://github.com/fgrehm/vagrant-notify/blob/master/lib/vagrant-notify/server.rb)), the [[summary]](http://www.unix.com/man-page/All/1/notify-send/) feature of notify-send is no longer available. This is what's shown as the title text. 

**Desired behavior:**
``root@vagrant-ubuntu-trusty-64:~# notify-send "Test title" "Test message"``
``{"title":"Test title": "message":"Test message"}``

**Current behavior:**
``root@vagrant-ubuntu-trusty-64:~# notify-send "Test title" "Test message"``
``{"message":"Test message"}``

The real notify-send application only uses the "summary" (title) feature if two or more non options arguments get passed to it. As shown in https://github.com/fgrehm/vagrant-notify#demo

Overall, your changes are awesome. By the way, don't worry about updating the rspec test scripts, I already have those ready based on your changes. 

Do let me know once you have the summary/title portion working of the new notify-send.erb/server.rb since this is an important thing to have working in order to have full notify-send compatibility.

**Comment by MekDrop** [comment]
Thanks for the feedback! It seems I forgot about such usage... I'll try to find a way to solve this issue.

**Comment by MekDrop** [comment]
Sorry for long delay. I think I have fixed the issue. I hope now everything works fine.

I have tested on Windows with http://vaskovsky.net/notify-send/ app and it works with required behavior however because that app doesn't supports long params, `sender_params_str` must be set by user (_`[-a {app_name}] [-u {urgency}] [-e {expire_time}] [-i {icon}] [-c {category}] [-h {hint}] {title} [{message}]`_). I hope this is not very big issue because most of notify-send apps supports both type of params.

**Pull request merged**
